In [2]:
import pandas as pd

In [3]:
import itertools
l_permutation = list(itertools.product([1, 2],[1,2],[1, 2],[1,2],[1, 2],[1,2],[1, 2],[1,2],[1, 2]))
df_permutation = pd.DataFrame(l_permutation,columns = ['beta','mu','p','delta','alpha','g_L','g_Z','g_Q','N_bar'])
df_permutation

     beta  mu  p  delta  alpha  g_L  g_Z  g_Q  N_bar
0       1   1  1      1      1    1    1    1      1
1       1   1  1      1      1    1    1    1      2
2       1   1  1      1      1    1    1    2      1
3       1   1  1      1      1    1    1    2      2
4       1   1  1      1      1    1    2    1      1
5       1   1  1      1      1    1    2    1      2
6       1   1  1      1      1    1    2    2      1
7       1   1  1      1      1    1    2    2      2
8       1   1  1      1      1    2    1    1      1
9       1   1  1      1      1    2    1    1      2
10      1   1  1      1      1    2    1    2      1
11      1   1  1      1      1    2    1    2      2
12      1   1  1      1      1    2    2    1      1
13      1   1  1      1      1    2    2    1      2
14      1   1  1      1      1    2    2    2      1
15      1   1  1      1      1    2    2    2      2
16      1   1  1      1      2    1    1    1      1
17      1   1  1      1      2    1    1    1      2
18      1   1  1      1      2    1    1    2      1
19      1   1  1      1      2    1    1    2      2
20      1   1  1      1      2    1    2    1      1
21      1   1  1      1      2    1    2    1      2
22      1   1  1      1      2    1    2    2      1
23      1   1  1      1      2    1    2    2      2
24      1   1  1      1      2    2    1    1      1
25      1   1  1      1      2    2    1    1      2
26      1   1  1      1      2    2    1    2      1
27      1   1  1      1      2    2    1    2      2
28      1   1  1      1      2    2    2    1      1
29      1   1  1      1      2    2    2    1      2
..    ...  .. ..    ...    ...  ...  ...  ...    ...
482     2   2  2      2      1    1    1    2      1
483     2   2  2      2      1    1    1    2      2
484     2   2  2      2      1    1    2    1      1
485     2   2  2      2      1    1    2    1      2
486     2   2  2      2      1    1    2    2      1
487     2   2  2      2      1    1    2    2      2
488     2   2  2      2      1    2    1    1      1
489     2   2  2      2      1    2    1    1      2
490     2   2  2      2      1    2    1    2      1
491     2   2  2      2      1    2    1    2      2
492     2   2  2      2      1    2    2    1      1
493     2   2  2      2      1    2    2    1      2
494     2   2  2      2      1    2    2    2      1
495     2   2  2      2      1    2    2    2      2
496     2   2  2      2      2    1    1    1      1
497     2   2  2      2      2    1    1    1      2
498     2   2  2      2      2    1    1    2      1
499     2   2  2      2      2    1    1    2      2
500     2   2  2      2      2    1    2    1      1
501     2   2  2      2      2    1    2    1      2
502     2   2  2      2      2    1    2    2      1
503     2   2  2      2      2    1    2    2      2
504     2   2  2      2      2    2    1    1      1
505     2   2  2      2      2    2    1    1      2
506     2   2  2      2      2    2    1    2      1
507     2   2  2      2      2    2    1    2      2
508     2   2  2      2      2    2    2    1      1
509     2   2  2      2      2    2    2    1      2
510     2   2  2      2      2    2    2    2      1
511     2   2  2      2      2    2    2    2      2

[512 rows x 9 columns]