In [32]:
import pandas as pd
import itertools

In [5]:
list = it

In [26]:
l = []

for beta in [1,2]:
    for mu in [1,2]:
        for p in [1,2]:
            for delta in [1,2]:
                for alpha in [1,2]:
                    for g_L in [1,2]:
                        for g_Z in [1,2]:
                            for g_Q in [1,2]:
                                for N_bar in [1,2]:
                                    l.append([beta,mu,p,delta,alpha,g_L,g_Z,g_Q,N_bar])
df = pd.DataFrame(l,columns=['beta','mu','p','delta','alpha','g_L','g_Z','g_Q','N_bar'])

In [28]:
df

     beta  mu  p  delta  alpha  g_L  g_Z  g_Q  N_bar
0       1   1  1      1      1    1    1    1      1
1       1   1  1      1      1    1    1    1      2
2       1   1  1      1      1    1    1    2      1
3       1   1  1      1      1    1    1    2      2
4       1   1  1      1      1    1    2    1      1
5       1   1  1      1      1    1    2    1      2
6       1   1  1      1      1    1    2    2      1
7       1   1  1      1      1    1    2    2      2
8       1   1  1      1      1    2    1    1      1
9       1   1  1      1      1    2    1    1      2
10      1   1  1      1      1    2    1    2      1
11      1   1  1      1      1    2    1    2      2
12      1   1  1      1      1    2    2    1      1
13      1   1  1      1      1    2    2    1      2
14      1   1  1      1      1    2    2    2      1
15      1   1  1      1      1    2    2    2      2
16      1   1  1      1      2    1    1    1      1
17      1   1  1      1      2    1    1    1      2
18      1   1  1      1      2    1    1    2      1
19      1   1  1      1      2    1    1    2      2
20      1   1  1      1      2    1    2    1      1
21      1   1  1      1      2    1    2    1      2
22      1   1  1      1      2    1    2    2      1
23      1   1  1      1      2    1    2    2      2
24      1   1  1      1      2    2    1    1      1
25      1   1  1      1      2    2    1    1      2
26      1   1  1      1      2    2    1    2      1
27      1   1  1      1      2    2    1    2      2
28      1   1  1      1      2    2    2    1      1
29      1   1  1      1      2    2    2    1      2
..    ...  .. ..    ...    ...  ...  ...  ...    ...
482     2   2  2      2      1    1    1    2      1
483     2   2  2      2      1    1    1    2      2
484     2   2  2      2      1    1    2    1      1
485     2   2  2      2      1    1    2    1      2
486     2   2  2      2      1    1    2    2      1
487     2   2  2      2      1    1    2    2      2
488     2   2  2      2      1    2    1    1      1
489     2   2  2      2      1    2    1    1      2
490     2   2  2      2      1    2    1    2      1
491     2   2  2      2      1    2    1    2      2
492     2   2  2      2      1    2    2    1      1
493     2   2  2      2      1    2    2    1      2
494     2   2  2      2      1    2    2    2      1
495     2   2  2      2      1    2    2    2      2
496     2   2  2      2      2    1    1    1      1
497     2   2  2      2      2    1    1    1      2
498     2   2  2      2      2    1    1    2      1
499     2   2  2      2      2    1    1    2      2
500     2   2  2      2      2    1    2    1      1
501     2   2  2      2      2    1    2    1      2
502     2   2  2      2      2    1    2    2      1
503     2   2  2      2      2    1    2    2      2
504     2   2  2      2      2    2    1    1      1
505     2   2  2      2      2    2    1    1      2
506     2   2  2      2      2    2    1    2      1
507     2   2  2      2      2    2    1    2      2
508     2   2  2      2      2    2    2    1      1
509     2   2  2      2      2    2    2    1      2
510     2   2  2      2      2    2    2    2      1
511     2   2  2      2      2    2    2    2      2

[512 rows x 9 columns]

In [19]:
df = pd.DataFrame(l,columns)

   beta  alpha
0     0      0
1     1      1
2     1      2
3     2      1
4     2      2

In [29]:
pd.DataFrame(list(itertools.product(*lists)), columns=['beta', 'mu', 'p'])

NameError: name 'itertools' is not defined

\beta	\mu	p	\delta	\alpha	g_P	g_Z	g_Q	Nbar
0.953469059	1.146508533	0.029529231	3.085253445	0.357382641	0.262856014	1.677804913	0.677794853	48.89592306

In [31]:
beta = 0.953469
mu = 1.146509
p = 0.029529
delta = 3.085253
alpha = 0.357383
g_L = 0.262856
g_Z = 1.677805
g_Q = 0.677795
Nbar = 48.49592

s_K = 0.4395005882352941

g_T = (1+g_L)*(1+g_Z)**(1/(1-alpha))*(1+g_Q)**(alpha/(1-alpha))-1
TFPgrowth = (g_T-(1-s_K)*g_L-s_K*(g_T+g_Q))
TFPgrowth

3.365443303851711